// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgALOxpVwbjH9hcumcaOhCBAXh2YxM6WU',
    appId: '1:14400873060:web:d859f6978f755f43f37571',
    messagingSenderId: '14400873060',
    projectId: 'dbnutrimap',
    authDomain: 'dbnutrimap.firebaseapp.com',
    databaseURL: 'https://dbnutrimap-default-rtdb.firebaseio.com',
    storageBucket: 'dbnutrimap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1q5LbVnUcvqNLrfBT7B9qmhESdCFiBbs',
    appId: '1:14400873060:android:bf825650dbcfdc5cf37571',
    messagingSenderId: '14400873060',
    projectId: 'dbnutrimap',
    databaseURL: 'https://dbnutrimap-default-rtdb.firebaseio.com',
    storageBucket: 'dbnutrimap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJPMuU55eMDjaI7v3ov18bbpnswltfvL8',
    appId: '1:14400873060:ios:bc5a45d937957c08f37571',
    messagingSenderId: '14400873060',
    projectId: 'dbnutrimap',
    databaseURL: 'https://dbnutrimap-default-rtdb.firebaseio.com',
    storageBucket: 'dbnutrimap.firebasestorage.app',
    iosBundleId: 'com.example.nutrimap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJPMuU55eMDjaI7v3ov18bbpnswltfvL8',
    appId: '1:14400873060:ios:bc5a45d937957c08f37571',
    messagingSenderId: '14400873060',
    projectId: 'dbnutrimap',
    databaseURL: 'https://dbnutrimap-default-rtdb.firebaseio.com',
    storageBucket: 'dbnutrimap.firebasestorage.app',
    iosBundleId: 'com.example.nutrimap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgALOxpVwbjH9hcumcaOhCBAXh2YxM6WU',
    appId: '1:14400873060:web:277907e584b9999bf37571',
    messagingSenderId: '14400873060',
    projectId: 'dbnutrimap',
    authDomain: 'dbnutrimap.firebaseapp.com',
    databaseURL: 'https://dbnutrimap-default-rtdb.firebaseio.com',
    storageBucket: 'dbnutrimap.firebasestorage.app',
  );

}